jhipster/generator-jhipster-blueprint

- .travis.yml
- generators/app/templates/generators/client/_index.js
With this missing `yarn link generator-jhipster-helloworld`, it will show that this generator doesn't work yet.
There are something to fix.
The error log is:
```
Trying to use blueprint generator-jhipster-helloworld
This is an existing project, using the configuration from your .yo-rc.json file 
to re-generate the project...
Trying to use blueprint generator-jhipster-helloworld
Installing languages: en, fr
events.js:183
throw er; // Unhandled 'error' event
^
Error: ERROR! Copying template ../../languages/templates/src/main/resources/i18n/messages_en.properties.ejs failed. [Error: ENOENT: no such file or directory, open '/home/travis/generator-jhipster-helloworld/generators/languages/templates/src/main/resources/i18n/messages_en.properties.ejs']
at Environment.error …
```
> Travis: add missing yarn link

- generators/app/index.js
- generators/app/input-validation.js
- test/input-validation.spec.js
- travis/samples/ngx-blueprint/.yo-rc.json
updated regex to match github's username validation, extracted validation methods into separate js file to support unit testing, added unit tests for github username validation and blueprint name validation.
Fix #8
> github username validation fix

- .eslintrc.json
- test/app.spec.js
- test/input-validation.spec.js
Simple PR **following https://github.com/jhipster/generator-jhipster-blueprint/pull/11** that declares mocha env for test directory and rename test to *.spec.js
> Clean tests config

- .travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/8859#issuecomment-440279014
> Travis: use test-integration folder to get entities

- .travis.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/9052
> Upgrade to Node 10.15.0

- generators/app/index.js
- generators/app/templates/generators/languages/_index.js
- generators/app/templates/test/_subgen.spec.ejs
- test/app.spec.js
Waiting this PR first: jhipster/generator-jhipster#9049
Related to https://github.com/jhipster/jhipster-vuejs/issues/132
> Blueprint languages

- .travis.yml
- generators/app/templates/_package.json
Fix https://github.com/jhipster/generator-jhipster-blueprint/issues/33
> Fix Travis builds, with different npm link

- .travis.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/9474
> Upgrade to Node 10.15.3

- generators/app/templates/_package.json
> Set minimal version of JHipster to 6.0.0

- README.md
- azure-pipelines.yml
> Migrate to Azure

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related with https://github.com/jhipster/generator-jhipster/pull/9816
> Update Node to 10.16.0

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related to jhipster/generator-jhipster#10173
> Update Node version to 10.16.1

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/10206
> Upgrade to Node 10.16.2

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/10236
> Update Node version to 10.16.3

- generators/app/index.js
- generators/app/templates/generators/_index.js.ejs
- generators/app/templates/test/_subgen.spec.ejs
This fixes #38 and fixes #10 too
Thanks @pvliss for enabling this with https://github.com/jhipster/generator-jhipster/pull/9942 !!
> Generates and enable tests for all entity-* subgenerators

- generators/app/index.js
- generators/app/templates/_package.json
- package-lock.json
- package.json
If fetching of version failed (e.g. no available network), prompt the user for the target version
Fixes #48
> Use a fixed version of JHipster that is retrieving during generation

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/10707
> update Node version to v12.13.0

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/10851
> Upgrade to NodeJS 12.13.1 LTS

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related with https://github.com/jhipster/generator-jhipster/pull/11067
> Update node to version 12.14.0 LTS

- generators/app/index.js
- test/app.spec.js
> Add app sub generator to blueprint generator

- .github/workflows/github-ci.yml
- .github/workflows/release-drafter.yml
- README.md
- generators/app/templates/_README.md
related to https://github.com/jhipster/generator-jhipster/issues/11935
> Change default branch from master to main

- .github/workflows/github-ci.yml
Related to https://github.com/jhipster/generator-jhipster/issues/12877
> Upgrade to Node 14.15.0 LTS

- .github/workflows/github-ci.yml
- generators/app/index.js
- generators/app/templates/_generator.yml
- generators/app/templates/_package.json
- generators/app/templates/eslintignore
- generators/app/templates/generators/_index.js.ejs
- generators/app/templates/gitignore
- generators/app/templates/test/_subgen.spec.ejs
- generators/app/templates/test/templates/ngx-blueprint/.yo-rc.json.ejs
- generators/app/templates/test/templates/vue-blueprint/.yo-rc.json.ejs
- test-integration/samples/ngx-blueprint/.yo-rc.json
- test-integration/samples/vue-blueprint/.yo-rc.json
- test/app.spec.js
close https://github.com/jhipster/generator-jhipster-blueprint/issues/200
> JHipster 7 upgrade

- generators/app/templates/_package.json
> New blueprints should be tagged jhipster-7

- LICENSE
- NOTICE
- related to https://github.com/jhipster/generator-jhipster/issues/17509
> Update License to 2022
